[[object_variable:object =`object_name`:template=`template_name`]]
[[$chunk:condition=`condition_flag`:alternate_chunk=`chunk_false`]]
[[banner:object=`image`]]
[[$view_business_detail_logo]]
[[business:object=`view_business_detail`]]